version: '3'
services:
        web:
                build: .
                ports:
                        - "8070:8070"
        mongo:
                image: "mongo"
                ports:
                        - "27017:27017"
