version: '3'
services:
        dionysus:
                build: .
                ports:
                        - "8070:8070"
        mongo:
                image: "mongo"
        dionysus-frontend:
                image: dionysus-frontend
                ports:
                        - "80:80"
